### ISSUE TITLE
Type Error: Cannot read property 'stage' of undefined.

### ISSUE THREAD

**Issue by nielsgl** [paulSambolin/serverless-enable-api-logs#6]
I'm getting this error:

```
  Type Error ---------------------------------------------

     Cannot read property 'stage' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'stage' of undefined
    at Class.module.exports.Class.extend.addStageVariables (/apps/lab-template-serverless/node_modules/serverless-enable-api-logs/src/index.js:33:50)
    at /.nodenv/versions/4.3.2/lib/node_modules/serverless/lib/classes/PluginManager.js:160:50
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at PluginManager.run (/.nodenv/versions/4.3.2/lib/node_modules/serverless/lib/classes/PluginManager.js:160:22)
    at Serverless.run (/.nodenv/versions/4.3.2/lib/node_modules/serverless/lib/Serverless.js:95:31)
    at /.nodenv/versions/4.3.2/lib/node_modules/serverless/bin/serverless:23:50
```

which corresponds to this line in the code:
```
var stage = this._serverless.service.defaults.stage;
```

I'm using the latest version of serverless.

**Comment by attinder-shf** [comment]
when fix for this issue will get merged?

**Comment by paulSambolin** [comment]
@attinderseesdragons @nielsgl the pull request has been merged to solve this issue.  Thank you @dshaneg !
